import { NextRequest } from 'next/server';
import { requireRole } from '@/server/auth';
import { json, errorResponse, readBody } from '@/server/utils';
import { GoogleGenAI } from '@google/genai';

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

export async function POST(req: NextRequest) {
  try {
    requireRole(req, 'admin');
    const { serviceName } = await readBody(req);

    if (!serviceName) {
      return json({ error: 'Service name is required' }, 400);
    }

    // Gemini se structured JSON data mangwa rahe hain
    const prompt = `You are an expert Indian digital service and government form assistant. 
    Based on the service name "${serviceName}", generate realistic and accurate fields for a service form in India.
    Return ONLY a valid JSON object with the following keys:
    - name: string (Clean official name)
    - category: string (e.g., "Govt Schemes", "Certificates", "Jobs", "Documents")
    - description: string (Short description of what this service is)
    - fees: array of objects with structure: [{ "category": "General", "governmentFee": number, "convenienceFee": number }, { "category": "SC/ST", "governmentFee": number, "convenienceFee": number }, { "category": "OBC", "governmentFee": number, "convenienceFee": number }]
    - documentsRequired: array of strings (e.g., ["Aadhaar Card", "Passport Photo"])
    `;

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
    });

    const textResponse = response.text || '{}';
    // Clean up code blocks if generated by model
    const cleanJson = textResponse.replace(/```json/g, '').replace(/```/g, '').trim();
    const serviceData = JSON.parse(cleanJson);

    return json({ success: true, data: serviceData });
  } catch (err) {
    return errorResponse(err, 'Failed to generate service details with AI');
  }
}